### PR TITLE
[HTTPCORE-611] Minor glitches with TimeValue.

### PR DESCRIPTION
**Pull request by garydgregory**
Add Locale methods.

### CODE REVIEW

**Comment by michael-o** [comment]
I am not really convinced that this is a good idea because this is not an end user API, but a developer API. There is no need to have anything locale specific. Same applies for all other places where we spit out large numbers.

**Comment by ok2c** [comment]
@michael-o Agreed. I see no need for locale specific methods.

**Comment by ok2c** [comment]
@garydgregory Do you intent to re-spin this PR?

**Comment by garydgregory** [comment]
Hi @ok2c 
Why does it need a re-spin? GitHub shows "This branch has no conflicts with the base branch"
@michael-o is not convinced and you gave a thumbs up.
I see this PR as addressing an edge-case but it does refactor the code nicely IMO.
Since this is a general utility class, providing some polish with a Locale API seems like a nice to have but not a must-have. 
Is the concern that the number separator is localized but the enum name is not?

**Comment by ok2c** [comment]
@garydgregory  I personally think that locale specific formatters / parsers is a mistake.

**Comment by garydgregory** [comment]
Well, if the both of you think that replacing all "%,d" with "%d" is the best way forward , I won't stop you ;-)

But focusing more narrowly on TimeValue, I could see adding in the future an API called toString(Locale) which would localize BOTH the number with separators and the enum name. 

Broadening again, we do not localize anything ATM through a resource bundle so this could be a first step in that direction.

**Comment by ok2c** [comment]
@garydgregory `SocketTimeoutExceptionFactory#create` uses `TimeValue#toString()` to generate an exception message. This message **must not** vary due to different locale settings.

**Comment by garydgregory** [comment]
OK, that's fine. That falls under my comment:

> Well, if the both of you think that replacing all "%,d" with "%d" is the best way forward , I won't stop you ;-)

**Comment by garydgregory** [comment]
Closing PR.

**Comment by michael-o** [comment]
It's ok closing for now.

**Pull request closed without merging**
