### PR TITLE
Update the method parameter from String to CharSequence.

### PR DESCRIPTION
**Pull request by wangkaish**
Update the method parameter of InetAddressUtils from String to CharSequence.

Sometimes I need to pass parts of a String(create a String slice) to this method instead of splitting the String into multiple pieces.

### CODE REVIEW

**Review by ok2c — CHANGES_REQUESTED** [review]
@wangkaish You have not run the build locally, have you? Please make sure that you also keep the old methods in place in order to ensure binary compatibility. Please deprecate the old methods in favor of the new ones

**Comment by wangkaish** [comment]
Hi, @ok2c  CI indicates that version compatibility check failed, but in fact the API is compatible, what do I do in this case?

**Comment by ok2c** [comment]
@wangkaish You do something like that https://github.com/ok2c/httpcomponents-core/commit/96ca1afe17af5e7e4973b21579adf9ebd5a10a69

**Comment by ok2c** [comment]
> but in fact the API is compatible
@wangkaish No, it is not. It is compile compatible but binary incompatible.

**Comment by wangkaish** [comment]
@ok2c There is a method named `isIPv4MappedIPv64Address` in InetAddressUtils, is that mean `isIPv4MappedIPv6Address`?

**Comment by ok2c** [comment]
@wangkaish There are style-check violations. Please address them. Please also add `@since 5.3` to a;; new methods. Otherwise looks good.

**Pull request merged**
