### PR TITLE
HTTPCLIENT-1916: Add URIBuilder.removeParameter

### PR DESCRIPTION
**Pull request by peterdettman**
https://issues.apache.org/jira/browse/HTTPCLIENT-1916 .

Note that I have marked the new method as "since 5.2".

### CODE REVIEW

**Comment by garydgregory** [comment]
May you please test edge cases like null and ""?

**Comment by peterdettman** [comment]
I'm happy to add such tests, but I'm a bit unclear what the expected behaviour ought to be. I'm inclined to require non-null, non-empty for `param` but actually other `URIBuilder` methods don't seem to exclude "" for a name (is that really permissible?). `BasicNameValuePair` guards only against null too).

**Comment by peterdettman** [comment]
@michael-o Some rationale was given by the submitter; I am merely picking up a _volunteers-wanted_ label.

**Review by ok2c — APPROVED** [review]

**Comment by ok2c** [comment]
> 
> 
> I'm happy to add such tests, but I'm a bit unclear what the expected behaviour ought to be. I'm inclined to require non-null, non-empty for `param` but actually other `URIBuilder` methods don't seem to exclude "" for a name (is that really permissible?). `BasicNameValuePair` guards only against null too).

@peterdettman I think just `null` check should be enough for now. The issue of name/value pairs with an empty name should be dealt with consistently across the entire library.

**Comment by peterdettman** [comment]
I've added a null guard for the argument, with accompanying test.

**Review by michael-o — APPROVED** [review]

**Pull request merged**
