### PR TITLE
HTTPCORE-588:Fixed concurrency issues

### PR DESCRIPTION
**Pull request by ITonyLi**
https://issues.apache.org/jira/browse/HTTPCORE-588

### CODE REVIEW

**Comment by ok2c** [comment]
@ITonyLi That would surely fix the problem but I was hoping this could be done without full synchronization on the object. I still would like to try fixing the bug with atomic primitives.

**Comment by ok2c** [comment]
@ITonyLi I would like to propose a different approach: ok2c/httpcore@b0154914af7058c865cec50d231ab6c4647a7884
Could you please review / test it with your code?

**Comment by ITonyLi** [comment]
OK, You code  is better.

**Comment by ok2c** [comment]
Superseded by 1e9d57e176b142ed05f48928e36c04149c1f9385

**Pull request closed without merging**
