### PR TITLE
HTTPCORE-648: Buffer array access respects the arrayOffset

### PR DESCRIPTION
**Pull request by carterkozak**

### CODE REVIEW

**Comment by michael-o** [comment]
Hod die you find this and would the but look like?

**Comment by michael-o** [comment]
How did you find this and how would it change behavior?

**Comment by carterkozak** [comment]
I noticed [this one]( https://github.com/apache/httpcomponents-client/pull/253) while reading through some code and decided to check for others around our calls to `Buffer.array()`. It's relatively rare for array-backed buffers to have an offset since it requires a call to `Buffer.slice()`, but I it's safest to keep this in mind to prevent edge case failures.

**Comment by carterkozak** [comment]
I'll add an hpack test that fails without reading array offset.

**Comment by bindul** [comment]
I wonder if the `arrayOffset` calls should be conditional based on `hasArray`. Based on the Javadoc [1] This is an optional operation and hence can throw `UnsupportedOperationException`.

[1] https://docs.oracle.com/javase/8/docs/api/java/nio/ByteBuffer.html#arrayOffset--

**Comment by carterkozak** [comment]
Absolutely, I've addressed this in #221

**Review by ok2c — APPROVED** [review]

**Pull request merged**
