### PR TITLE
Master pom cleanup

### PR DESCRIPTION
**Pull request by michael-o**
This completey aligns with Parent 12 and removes/unifies duplicate configuration.

If approved, it will be ported to 5.1.x too.

### CODE REVIEW

**Review by ok2c — APPROVED** [review]
@michael-o I did some very superfluous review of the changes and found nothing obviously wrong. We will see how well the release process goes. Please go ahead and merge it.

**Comment by michael-o** [comment]
Merged into master, 5.1.x will follow.

**Comment by ok2c** [comment]
@michael-o You do not really need to do that. I regularly re-base 5.1.x off master.

**Comment by michael-o** [comment]
It's almost done anyway, but will keep that in mind for the future. Thanks for the heads up.

**Comment by ok2c** [comment]
@michael-o There is slight problem. It looks like the `javadoc` plugin does not work well with the new setup. 

I am seeing those warnings when running `mvn clean javadoc:javadoc` 

```
[INFO] --- maven-javadoc-plugin:3.2.0:javadoc (default-cli) @ httpcore5 ---
[INFO] Toolchain in maven-javadoc-plugin: JDK[/opt/oracle-jdk-1.7.0]
[INFO] No previous run data found, generating javadoc.
[INFO] 
2 warnings
[WARNING] Javadoc Warnings
[WARNING] javadoc: warning - Error fetching URL: https://hc.apache.org/httpcomponents-core-5.0.x//httpcore5/apidocs/package-list
[WARNING] javadoc: warning - Error fetching URL: https://hc.apache.org/httpcomponents-core-5.0.x//httpcore5-h2/apidocs/package-list
```
If I change link references to use `http` everything appears to be good again
```
      <plugin>
        <artifactId>maven-javadoc-plugin</artifactId>
        <configuration>
          <links>
            <link>http://hc.apache.org/httpcomponents-core-5.0.x/httpcore5/apidocs/</link>
            <link>http://hc.apache.org/httpcomponents-core-5.0.x/httpcore5-h2/apidocs/</link>
          </links>
        </configuration>
      </plugin>
```
We need to fix this one.

**Comment by michael-o** [comment]
That's weird. I will have a look whether I can reproduce this here.

**Comment by michael-o** [comment]
OK, I know why this is failing for you, but not for me:
```
D:\Entwicklung\Projekte\httpcomponents-core5 [master ≡]> mvn -v
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: D:\Entwicklung\Programme\apache-maven-3.5.4\bin\..
Java version: 1.7.0_272, vendor: Azul Systems, Inc., runtime: C:\Program Files\Zulu\zulu-7\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

You still use Oracle JDK 7u80 instead of OpenJDK with has TLS 1.2 built in. Would you mind to use Azul Zulu or something else for Java 7 or do you still want to change the links to http://?

**Comment by ok2c** [comment]
@michael-o I will see if I can upgrade my current JDK 1.7 to something newer.

**Pull request closed without merging**
