### PR TITLE
Use Locale.ROOT for case-conversion.

### PR DESCRIPTION
**Pull request by arturobernalg**

### CODE REVIEW

**Comment by michael-o** [comment]
I wonder whether this makes a difference since all month names are in English.

**Comment by arturobernalg** [comment]
> I wonder whether this makes a difference since all month names are in English.

AFAIK none. Just I try to be consistent in all the HttpComponents.

**Review by ok2c — CHANGES_REQUESTED** [review]
@arturobernalg `SimpleDateFormat` should be replaced with Java 8 `DateTimeFormatter`. I already upgraded client but did not get around to upgrading core, Please do that instead.

**Comment by arturobernalg** [comment]
> DateTimeFormatter
I've created HTTPCORE-697 to start to work on that
TY

**Comment by arturobernalg** [comment]
> @arturobernalg `SimpleDateFormat` should be replaced with Java 8 `DateTimeFormatter`. I already upgraded client but did not get around to upgrading core, Please do that instead.

Close this PR in favor of https://github.com/apache/httpcomponents-core/pull/324

**Pull request closed without merging**
