### PR TITLE
Rename all classes prefixed with "H2..." to "Http2...".

### PR DESCRIPTION
**Pull request by garydgregory**
- Rename H1Config to Http1Config.
- Rename methods from *H2* to *Http2*
- Rename ivars from *H2* to *Http2*
- Rename ivars from h2* to http2*
- As above for H1/h1.

### CODE REVIEW

**Comment by ok2c** [comment]
@garydgregory Why did decide to rename `H2` to `http2`? `H2` is the official protocol identifier. More importantly why did you decide to do it so late in the release process?

**Comment by garydgregory** [comment]
Hi @ok2c ,

TBH, I had not looked at HTTP/2 close enough to learn that "The string "h2" identifies the protocol where HTTP/2 uses Transport Layer Security (TLS) [TLS12]." according to https://http2.github.io/http2-spec/

Are you saying all classes that start with "H2" have to do with TLS? If yes, then we should not rename. If not, then we should rename to at least distinguish "h2" vs. HTTP/2 classes. If none of the classes are specific to TLS then we can rename them all. Please advise.

If we have classes called "H2", should we have some called "H2C" to distinguish anything related to clear text? 

The timing of my PR is of coincidental timing, we are all busy folks.

Thank you,
Gary

**Comment by ok2c** [comment]
@garydgregory I am not sure I can agree to `H2` protocol identifier being in any way specific to `TLS`. It is the identifier of a protocol that implies the use of`TLS`.

**Comment by michael-o** [comment]
Does HTTP/2 really imply TLS? I though that there is `h2` and `h2c` for that. HTTP/2 is the wire format and the latter two the transport implementation.

**Comment by garydgregory** [comment]
> Does HTTP/2 really imply TLS?

No, see https://http2.github.io/faq/

>I am not sure I can agree to H2 protocol identifier being in any way specific to TLS. It is the identifier of a protocol that implies the use of TLS.

Well, OK, but like you say "H2" implies that you are in TLS territory.

I restate with question:

>Are you saying all classes that start with "H2" have to do with TLS? If yes, then we should not rename. If not, then we should rename to at least distinguish "h2" vs. HTTP/2 classes. If none of the classes are specific to TLS then we can rename them all. Please advise.

Gary

**Comment by ok2c** [comment]
@garydgregory And I have to repeat the same answer. `H2` is the standard protocol identifier for HTTP/2. In the context of `ALPN TLS` it implies the use of `TLS` but it does not make it `TLS` specific.

**Comment by rschmitt** [comment]
@garydgregory I agree with @ok2c. It's quite common to refer to HTTP/2 as "h2," in part because the former is a mouthful and in part because no one seems to see it as an abuse of terminology.

**Comment by ok2c** [comment]
@garydgregory Do you intend to merge this change-set or re-work it? When can I proceed with the release?

**Comment by garydgregory** [comment]
Hi @ok2c, @rschmitt, and all:

Let's step back and consider an easy case: "H1Config". This is the only class prefixed with "H1". Is "H1" known a well known abbreviation? Are there other version 1 specific types that should be thus named? If "H1" is not well known, should this H1 class be renamed and to what HttpConfig or Http1Config? I could see keeping H1 if we use H2 all over (see below.)

Then the broader topic of "H2" vs. "Http2" prefixes: Is there any rational for this inconsistency? If not, then all types should share the same prefix, I do not care which one.

WDYT?

**Comment by michael-o** [comment]
I have never heard of `H1`, I'd really stick to `HttpConfig` is this case. As for HTTP/2, I agree with Gary that prefixes should be consistent. Either one.

**Comment by ok2c** [comment]
@garydgregory I do not have much of a problem with `H1` -> `Http1`. I personally see no reason to do anything about `H2` vs `Http2` inconsistency. It did not seem to bother anything all that much. But if you absolutely have to do it, my preference would be to use `H2` prefix.

**Comment by michael-o** [comment]
@ok2c Can you actually tell why you prefer `H2`. As for readability, `H2` looks awkward in the code (at least to me).

**Comment by ok2c** [comment]
@michael-o It is shorter and more importantly all core HTTP/2 classes have `H2` prefix already.

**Comment by michael-o** [comment]
That's a point.

**Comment by garydgregory** [comment]
OK, so it seems we all agree all HTTP/2 types should be prefixed with "H2" and that types currently prefixed with "Http2" should be renamed to start with "H2". I will propose another PR today.

**Comment by garydgregory** [comment]
Closing. Replaced by https://github.com/apache/httpcomponents-core/pull/130

**Pull request closed without merging**
