### PR TITLE
Rename Http2* types to H2*.

### PR DESCRIPTION
**Pull request by garydgregory**
Rename Http2* types to H2*.
Next to consider: Http1 and H1 types.

### CODE REVIEW

**Comment by ok2c** [comment]
@garydgregory I am completely lost here. Why instead of renaming a single `H1Config` to `Http1Config` did you decide to rename dozens unrelated classes?

**Comment by garydgregory** [comment]
I'm a bit a loss on how to address your comment after I've asked several times and commented back (to myself and others) on the dev mailing list for clarification on the current nomenclature. So again: I find it lame and confusing to prefix some classes with H2 instead of Htt2 while leaving other types prefixed with Http1 (instead of H1, of which there is one.) The naming should be, IMO, consistent: If we prefix HTTP/2 classes with "H2", then it makes sense to prefix HTTP/1 classes with "H1".

**Comment by michael-o** [comment]
Here is even more inconsistency: the module is called `http5-h2`, but the package names contain `http2`.

**Comment by garydgregory** [comment]
@michael-o do you have a change suggestion?

**Comment by michael-o** [comment]
@garydgregory I would apply the same logic as do did to the classnames: either `H2` or `Http2`. From a user's POV it is confusing/inconsistent.

**Comment by ok2c** [comment]
@garydgregory 
`h2` is the standard protocol identifier for `http/2` as defined by IANA. As far as I am concerned `h2` and `http/2` are synonymous.The protocol identifier for `http/1.1` is, well, `http/1.1`, not `h1`. There is no protocol with identifier `h1`.   

https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids

Oleg

**Comment by ok2c** [comment]
@garydgregory It has been three weeks without any progress and more importantly any clear objective and purpose for this change. What are your plans about it?

**Comment by garydgregory** [comment]
Hi @ok2c 
I happy to merge this PR as is.
It feels to me your comment ignore the emails exchanged on this topic.
Please see the email thread "Http2, H2, Http, Http, H1" on the dev mailing list.

**Comment by garydgregory** [comment]
Closing since this was done in a different commit.

**Pull request closed without merging**
