### PR TITLE
HTTPCORE-746: fix deadlock with Java Virtual Threads

### PR DESCRIPTION
**Pull request by marsqing**
As reported in [HTTPCORE-746](https://issues.apache.org/jira/projects/HTTPCORE/issues/HTTPCORE-746?filter=allopenissues), blocking operations in synchronized block/method will make the platform thread pinned to the virtual thread and not be able to carry other virtual threads. Remove the synchronized in AbstractConnPool will free the platform threads which are carrying virtual threads which are waiting for available connections in the pool. 

Also reviewed other synchronized blocks/methods in httpcomponent-core and IMHO won't cause the above problem. Because either no blocking opertions in them or they won't block on the same resource.

### CODE REVIEW

**Comment by arturobernalg** [comment]
While reviewing your changes, I noticed there might be other parts of the codebase where the use of synchronized (this) could potentially cause similar issues. Would it be worth considering similar modifications in these areas as well?

**Comment by marsqing** [comment]
The synchronized in AbstractConnPool is probably the most problematic one because blocking/awaiting for available connections is so common. The most "correct" way is to replace all synchronized with lock. But as I don't have thorough understanding of the codebase, I'm afraid I won't be able to make the best choice. For example, the [synchronized](https://github.com/apache/httpcomponents-core/blob/45d8a4cb391f591bb8d380b820437b651435774f/httpcore-nio/src/main/java/org/apache/http/nio/protocol/HttpAsyncService.java#L431) in HttpAsyncService is on a State object, should I add a ReentrantLock field in State class or there are better ways? I've reviewed all synchronized in httpcomponent-core and I think they are ok or at least much less problematic than the one in AbstractConnPool.

**Comment by ok2c** [comment]
@marsqing I am also of option that we either should replace `synchronized` with ReentrantLock consistently across the entire code base or not at all. My proposal is to leave 4.x be and make sure 5.x works correctly with newest JREs.

**Comment by marsqing** [comment]
I see. So I guess 4.x is effectively EOL? If so, we'd better migrate to 5.x ASAP.

**Comment by ok2c** [comment]
> I see. So I guess 4.x is effectively EOL? If so, we'd better migrate to 5.x ASAP.

No, it is not. We will continue to support it but there will be no new development beyond critical and security issues.

**Pull request closed without merging**
