### PR TITLE
Update the pointer of Continuation's headerBuffer after copying the payload

### PR DESCRIPTION
**Pull request by CoolTomatos**
This pull request fixes [HTTPCORE-772](https://issues.apache.org/jira/browse/HTTPCORE-772)

### CODE REVIEW

**Comment by CoolTomatos** [comment]
Hi @ok2c, thanks for the reply. 
Just pushed a commit to fix the style issue.
Will try to add some test coverage tomorrow. Was looking at APIs how to setup some header frames and continuation frames for the test case.

**Comment by CoolTomatos** [comment]
Hi @ok2c added a small test case that would fail without my fix and passes with my fix. Please have a look!

**Comment by ok2c** [comment]
@CoolTomatos cherry-picked to `5.3.x`

**Comment by CoolTomatos** [comment]
> @CoolTomatos cherry-picked to `5.3.x`

Hi @ok2c do we have a rough timeline when 5.3.2 will be released?

**Comment by ok2c** [comment]
@CoolTomatos It is a nasty one but not severe enough for an emergency release in my opinion. I would release 5.3.2 sometime in January.

**Pull request merged**
