### PR TITLE
Read specified number of bytes from HttpEntity

### PR DESCRIPTION
**Pull request by andriymahats**
https://issues.apache.org/jira/browse/HTTPCLIENT-2098

### CODE REVIEW

**Comment by ok2c** [comment]
@andriymahats Looks reasonable. Could you please fix style check violations, please?

**Comment by andriymahats** [comment]
@ok2c Fixed style check violations.

**Comment by ok2c** [comment]
@andriymahats Many thanks for this contribution.

**Comment by andriymahats** [comment]
@ok2c My pleasure.

**Pull request merged**
