### PR TITLE
Add and use TimeValue await(), awaitTermination() and get() methods.

### PR DESCRIPTION
**Pull request by garydgregory**

### CODE REVIEW

**Comment by michael-o** [comment]
@ok2c I absolutely agree here. Separation of concerns must apply here.

**Comment by garydgregory** [comment]
@ok2c & @michael-o 

I will see your separation of concerns and raise you breaking encapsulation ;-)

Let's step back, look at this from the 10,000 ft level and dive back in.

Why do we even have a `TimeValue` class?

Because for some completely absurd reason we are planning to release a MAJOR NEW version of a library, in 2020, based on Java 7. This means we cannot use Java 8's `java.util.Duration` class. We are actually telling people that Java 7 is so important that it is OK to create new projects that depend on Java 7 while even Java 8 is EOL. FWIW, a lof of the customers I see can't get to Java 11 fast enough.

To make matters worse, we are talking of requiring Java 8 for 5.1. So as soon as that happens people are naturally going to see TimeValue instead of Duration all over our API and wonder what kind of silliness that is. Once 5.0 is out, the API is set in stone, so for playing nice with Java 8, we'd have to add Duration APIs where we have TimeValue. Not a pretty sight.

So, now, back down to the bits. We've had to open up the guts of TimeValue with accessors like getDuration() and getTimeUnit() in order to play nice with API that take a long and a TimeUnit. That's not pretty and I claim this kind of pattern effectively breaks (in call sites) the encapsulation offered by the TimeValue abstraction. So instead of all call sites cracking a TimeValue egg open each time it needs to call some JRE concurrent APIs, I though it cleaner to flip the call around as this PR provides. You can see, especially in the tests, how much the call sites are cleaned up by this, that's IMO YMMV of course.

If it were up to me, I'd make 5.0 depend on Java 8 and use Duration instead of TimeValue. Bam! Simple, expected, done.

Thoughts?

**Comment by michael-o** [comment]
@garydgregory There are several issue here, I will go in brief, but this discussion should really be on the dev list.

1. The class version freeze happened when 5.0 was started to be developed. This is a fair deal for everyone to have some long term planning. Yes, Java 7 has been overcome by events. Always consider that this is not a toy project. A LOT of people and software depend on it. I can show you 10 000+ users in my company using HttpClient 4.4.x every single day.
2. Generally, HttpComponents major release takes a long time due to the complexity/amount of code, little community (3-5 people) and being a backend library people only care when it is broken.
3. Java 8 is far not EOL, only Oracle's binary JDK is. There are plenty alternatives until 2025 for Java 8 on various platforms.

What we could do is consider 5.0 as an interim release, fixing deficiencies of the 4.x line which will live for a year and then we make another baseline improvement, fix 5.x deficiencies and move to 6.0 with Java 8. Our turnarounds are slow, but this is not a bad thing. Moving fast does not mean you are delivering quality.

**Comment by ok2c** [comment]
@garydgregory Encapsulation cannot be used as an excuse here. By moving the offending methods to another class we are not going to expose any internal private structures.

**Comment by michael-o** [comment]
I'd recommend to close this as it breaks separation of concerns.

**Pull request closed without merging**
