### PR TITLE
Change methods  to void whose return values are never used when called.

### PR DESCRIPTION
**Pull request by arturobernalg**

### CODE REVIEW

**Comment by ok2c** [comment]
@arturobernalg I am sorry but I see no benefits in this change-set. What does it improve? Just eliminates a few warnings in your IDE?

**Comment by arturobernalg** [comment]
> @arturobernalg I am sorry but I see no benefits in this change-set. What does it improve? Just eliminates a few warnings in your IDE?

Hi @ok2c 
Well, IMO why we should return a value does not used? Maybe avoid possible error at the future and simplify the code, just that.
TY

**Comment by michael-o** [comment]
> 
> 
> @arturobernalg I am sorry but I see no benefits in this change-set. What does it improve? Just eliminates a few warnings in your IDE?

In most cases it causes confusion. One might think that this is a bug. I would address this and move on.

**Comment by ok2c** [comment]
@arturobernalg Just because the return value is not used at the moment does not mean it is useless. I do not see how your changes would simplify anything or make anything less error-prone.

**Comment by arturobernalg** [comment]
> @arturobernalg Just because the return value is not used at the moment does not mean it is useless. I do not see how your changes would simplify anything or make anything less error-prone.

Hi @ok2c 
IMO the simple fact of have an unused return value it's a programing error or mistake. What it the point of have something that will not use? Off course this is very subjective ;)
TY

**Comment by ok2c** [comment]
> What it the point of have something that will not use? Off course this is very subjective
@arturobernalg Methods that you want to modify return data that represents the result of an operation. Just because it is not being used at the moment does not mean it cannot be used in the future or is generally useless.

**Comment by arturobernalg** [comment]
> What it the point of have something that will not use? Off course this is very subjective
> @arturobernalg Methods that you want to modify return data that represents the result of an operation. Just because it is not being used at the moment does not mean it cannot be used in the future or is generally useless.

Hi @ok2c 
I'm gonna close the PR.
TY

**Pull request closed without merging**
