### PR TITLE
Master try w res and more

### PR DESCRIPTION
**Pull request by garydgregory**
Each commit in this PR comprise one kind of cleanup/change:
- Use try-with-resources.
- Use diamonds.
- Add missing @override.
- Make better use of Map APIs.
- Remove redundant modifiers. …
- Use Collections.addAll() API instead of loops.
- Remote extra semicolons (;).

### CODE REVIEW

**Review by michael-o — COMMENTED** [review]
You have removed static on some elements. Why?

**Comment by garydgregory** [comment]
> You have removed static on some elements. Why?

Because they are completely redundant. Please see the commit comment for that specific commit.

**Comment by michael-o** [comment]
> > You have removed static on some elements. Why?
> 
> Because they are completely redundant. Please see the commit comment for that specific commit.

So the strings in an interface are static final by default?

**Review by ok2c — APPROVED** [review]

**Comment by carterkozak** [comment]
All variables defined in an interface are "public static final".

**Comment by garydgregory** [comment]
> > > You have removed static on some elements. Why?
> > 
> > 
> > Because they are completely redundant. Please see the commit comment for that specific commit.
> 
> So the strings in an interface are static final by default?

It would not be much of a contract otherwise! ;-)

The JLS say that members in an interface are implicitly public, static, and final.

**Pull request merged**
