### PR TITLE
Add infrastructure for Docker-enabled integration tests

### PR DESCRIPTION
**Pull request by rschmitt**

### CODE REVIEW

**Comment by michael-o** [comment]
Rejecting this PR for two reasons:

* It is not portable, it fails everywhere where Docker ist not available/installed:

```
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.31.0:start (star                                      t-httpbin) on project httpcore5-testing: Execution start-httpbin of goal io.fabr                                      ic8:docker-maven-plugin:0.31.0:start failed: No <dockerHost> given, no DOCKER_HO                                      ST environment variable, no read/writable '/var/run/docker.sock' or '//./pipe/do                                      cker_engine' and no external provider like Docker machine configured -> [Help 1]
```

E.g. on:

```
[mosipov@mika-ion ~/Projekte/httpcomponents-core]$ mvn -v
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /usr/local/share/java/maven
Java version: 1.8.0_222, vendor: Oracle Corporation, runtime: /usr/local/openjdk8/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "freebsd", version: "11.3-release-p3", arch: "i386", family: "unix"
```

* I highly doubt that the images pulled ran be routed through a repo manager, thus it requires outbound internet access making the tests not selfcontained.

**Comment by ok2c** [comment]
@rschmitt This is **super, super** cool! It does have to be in a special profile, though.

Is there any chance we could keep `openjdk7` target until we are ready to drop Java 1.7 support?

**Comment by rschmitt** [comment]
> Is there any chance we could keep `openjdk7` target until we are ready to drop Java 1.7 support?

I think I can pull that off. Although I thought we _were_ ready to drop Java 1.7 support, based on our conversation about JUnit 5. (Note that the Docker plugin itself is what requires JDK8.)

**Comment by michael-o** [comment]
> 
> 
> > Is there any chance we could keep `openjdk7` target until we are ready to drop Java 1.7 support?
> 
> I think I can pull that off. Although I thought we _were_ ready to drop Java 1.7 support, based on our conversation about JUnit 5. (Note that the Docker plugin itself is what requires JDK8.)

I think this heavily depends on how long we want to support 4.x. Please consider that Java 7 will still receive support from many vendors for the years to come.

**Comment by ok2c** [comment]
> > Is there any chance we could keep `openjdk7` target until we are ready to drop Java 1.7 support?
> 
> I think I can pull that off. Although I thought we _were_ ready to drop Java 1.7 support, based on our conversation about JUnit 5. (Note that the Docker plugin itself is what requires JDK8.)

We are ready but we cannot do it this very moment. We can branch off 5.1 immediately after 5.0 GA and upgrade its minimal JRE level to 1.8 or 11.

**Comment by garydgregory** [comment]
If we are going to do 5.1 on Java 8 it is likely that we will want to do
API clean ups using lambdas, java.time and who knows what else. So why not
save the hassle and base 5.0 on Java 8?

Gary

**Comment by michael-o** [comment]
> 
> If we are going to do 5.1 on Java 8 it is likely that we will want to do API clean ups using lambdas, java.time and who knows what else. So why not save the hassle and base 5.0 on Java 8? Gary

Several reasons:

* Changing now bytecode version in a very late state maybe problematic for users. This isn't just class renames
* Rewriting existing code immediately makes backports really hard.

Deprecating 5.0 right after the immediate release of 5.1 will drop trust in the community. They will ask, why did you that so quickly.

I know commercial software where the current release version still uses Commons HttpClient 3.x. They just started testing phase with us with a new Eclipse RCP 4.10.x and HttpClient 4.5.x bases release. Expect that a lot of software remains untouched in their grounds for 5 to 10 years.

**Comment by ok2c** [comment]
> Deprecating 5.0 right after the immediate release of 5.1 will drop trust in the community. They will ask, why did you that so quickly.

There is absolutely no need to deprecate 5.0 any time soon. We can maintain it as long as there is demand for Java 1.7 compatibility.

**Comment by michael-o** [comment]
> 
> 
> > Deprecating 5.0 right after the immediate release of 5.1 will drop trust in the community. They will ask, why did you that so quickly.
> 
> There is absolutely no need to deprecate 5.0 any time soon. We can maintain it as long as there is demand for Java 1.7 compatibility.

What will happen to the 4.x branch? So maintaining three branches in parallel?

**Comment by ok2c** [comment]
> > > Deprecating 5.0 right after the immediate release of 5.1 will drop trust in the community. They will ask, why did you that so quickly.
> > 
> > 
> > There is absolutely no need to deprecate 5.0 any time soon. We can maintain it as long as there is demand for Java 1.7 compatibility.
> 
> What will happen to the 4.x branch? So maintaining three branches in parallel?

We do not have much choice, do we? New features would however be added to master (5.1) only.

**Comment by michael-o** [comment]
> 
> 
> > > > Deprecating 5.0 right after the immediate release of 5.1 will drop trust in the community. They will ask, why did you that so quickly.
> > > 
> > > 
> > > There is absolutely no need to deprecate 5.0 any time soon. We can maintain it as long as there is demand for Java 1.7 compatibility.
> > 
> > 
> > What will happen to the 4.x branch? So maintaining three branches in parallel?
> 
> We do not have much choice, do we? New features would however be added to master (5.1) only.

That seems reasonable to me.

**Comment by rschmitt** [comment]
> We are ready but we cannot do it this very moment. We can branch off 5.1 immediately after 5.0 GA and upgrade its minimal JRE level to 1.8 or 11.

Would 5.1 include breaking API changes from 5.0? If not, could we develop a separate `jdk8` library that adds `CompletableFuture` support, the way we have a separate library for reactive integration?

**Comment by ok2c** [comment]
> > We are ready but we cannot do it this very moment. We can branch off 5.1 immediately after 5.0 GA and upgrade its minimal JRE level to 1.8 or 11.
> 
> Would 5.1 include breaking API changes from 5.0? If not, could we develop a separate `jdk8` library that adds `CompletableFuture` support, the way we have a separate library for reactive integration?

No, it would not, as long as we still want to call it 5.1 but we can start adding Java 1.8 features such as `CompletableFuture` and deprecating old functionality in favor of new one.

**Comment by rschmitt** [comment]
Any other comments on the latest revision? The [latest build](https://travis-ci.org/rschmitt/httpcomponents-core/builds/633430619) should show that both concerns have been addressed (non-default profile and openjdk7 build support).

**Comment by ok2c** [comment]
> Any other comments on the latest revision? The [latest build](https://travis-ci.org/rschmitt/httpcomponents-core/builds/633430619) should show that both concerns have been addressed (non-default profile and openjdk7 build support).

@rschmitt Looks good to me. 
Any idea how much slower does this make integration test execution on Travis CI?

**Comment by rschmitt** [comment]
> Any idea how much slower does this make integration test execution on Travis CI?

It adds about one minute.

**Pull request merged**
