### PR TITLE
Deprecate org.apache.hc.core5.util.Args.notNull(T, String) in favor of

### PR DESCRIPTION
**Pull request by garydgregory**
java.util.Objects.requireNonNull(T, String).

### CODE REVIEW

**Comment by ok2c** [comment]
@garydgregory What does this buy us exactly?

**Comment by garydgregory** [comment]
I'll answer with the question "Why do we duplicate code that is in the JRE?"
There no reason to do so. Furthermore, this invites folks to wonder why we do so. Why do we do that? Is our version better? No, it's just duplication. Duplication is a code smell.

**Comment by ok2c** [comment]
> Furthermore, this invites folks to wonder why we do so

Is there any  specific evidence of any folks wondering?

Based on this flawed logic we should throw away the entire library because "duplicate code that is in the JRE".

I am strongly -1 on this change-set in its present form. Feel free to replace functionality provided by `Args` and deprecate the entire class.

**Comment by michael-o** [comment]
Here is my opinion and I tend to agree with @ok2c :

1. `Args` still contains a lot of functionality cannot be replaced with plain Java
2. It decreases tge readability a bit because of the former

This is what would be a real improvement:

```
    public static <T> T notNull(final T argument, final String name) {
        if (argument == null) {
            throw NullPointerException(name + "cannot be null");
        }
        return argument;
    }
```

A mere argument nate is a bit too cheap. Nested here, you could use `Objects`.

**Comment by garydgregory** [comment]
It seems there is a severe disconnect here which I can only attribute to the the communication medium, if only we had a water cooler...

From @michael-o: "Args still contains a lot of functionality cannot be replaced with plain Java"
From @ok2c: "There are still a lot of functionality in Args that presently cannot be replaced by a JRE provided method."

I do _not_ and the patch does _not_ remove the Args class I do am not advocating to replace all of it with JRE code; this patch is about the one API which is a clear duplicate of JRE functionality and reeks of NIH syndrome. 

I'm not even sure how to qualify this from @ok2c's:
```
Based on this flawed logic we should throw away the entire library because "duplicate code that is in the JRE".
```
Flame bait I guess.

**Comment by michael-o** [comment]
@garydgregory I never assumed/expected. that you goal was to remove this class, but replace redundant parts. All I am saying is that replacing one line with another will not improve a lot. The improvement I would see is the reduction of the rudandant repitition of "cannot be null".

**Pull request closed without merging**
