### PR TITLE
4.4.x use better map apis and more

### PR DESCRIPTION
**Pull request by garydgregory**
Each commit in this PR comprise one kind of cleanup/change:

- Make better use of Map APIs.
- Remove redundant modifiers.
- Use Collections.addAll() API instead of loops.
- Remove redundant returns.
- No need to explicitly declare an array when calling a vararg method.
- Remote extra semicolons (;).

### CODE REVIEW

**Comment by michael-o** [comment]
what is the purpose of this PR?

**Comment by garydgregory** [comment]
Darn, I picked up to much history.

**Comment by garydgregory** [comment]
> what is the purpose of this PR?

@michael-o 
Please see updated description.

**Comment by garydgregory** [comment]
> Darn, I picked up to much history.

Fixed my git.

**Comment by carterkozak** [comment]
Out of curiosity, did you make these changes manually, or using an automated tool?

**Comment by michael-o** [comment]
Are these present on 5.x?

**Comment by garydgregory** [comment]
> Out of curiosity, did you make these changes manually, or using an automated tool?

I started with Eclipse's clean ups and then made small adjustments by hand for clarity and added some comments.

**Comment by garydgregory** [comment]
> Are these present on 5.x?

Yes, please see my other PRs, there are 4 PRs in total.

**Review by ok2c — APPROVED** [review]

**Pull request merged**
