### PR TITLE
HTTPCORE-698 - Migrate Test to Unit 5.

### PR DESCRIPTION
**Pull request by arturobernalg**

### CODE REVIEW

**Comment by michael-o** [comment]
Guys, I am still not sure whether this is the right decision for now since we are likely going to maintain 5.1.x on Java 7 for some time... This change will make backports harder. WDYT?

**Comment by garydgregory** [comment]
I find JUnit 5 easier to deal with, usually. I think we should do it.

**Review by ok2c — APPROVED** [review]

**Comment by ok2c** [comment]
@arturobernalg Looks good to me. 

> Guys, I am still not sure whether this is the right decision for now since we are likely going to maintain 5.1.x on Java 7 for some time... This change will make backports harder. WDYT?

@michael-o We already started using lambdas in tests, so automatic merging between branches is going to be difficult anyway. so, I do not see this as a  deal breaker.

**Comment by arturobernalg** [comment]
> @arturobernalg Looks good to me.
> 
> > Guys, I am still not sure whether this is the right decision for now since we are likely going to maintain 5.1.x on Java 7 for some time... This change will make backports harder. WDYT?
> 
> @michael-o We already started using lambdas in tests, so automatic merging between branches is going to be difficult anyway. so, I do not see this as a deal breaker.

can I help you?

**Comment by michael-o** [comment]
> @arturobernalg Looks good to me.
> 
> > Guys, I am still not sure whether this is the right decision for now since we are likely going to maintain 5.1.x on Java 7 for some time... This change will make backports harder. WDYT?
> 
> @michael-o We already started using lambdas in tests, so automatic merging between branches is going to be difficult anyway. so, I do not see this as a deal breaker.

Then go on with the merge

**Comment by ok2c** [comment]
> can I help you?

@arturobernalg No immediate help is needed. But if you really want to help, please spend less time changing code style based on personal taste or preferences and spend more time improving functionality. For instance, migrating HttpClient APIs from `java.util.Date` to `java.time.Instant` would make a very good contribution..

**Comment by arturobernalg** [comment]
> > can I help you?
> 
> @arturobernalg No immediate help is needed. But if you really want to help, please spend less time changing code style based on personal taste or preferences and spend more time improving functionality. For instance, migrating HttpClient APIs from `java.util.Date` to `java.time.Instant` would make a very good contribution..

Hi @ok2c 
Got it. 
TY

**Pull request merged**
