### PR TITLE
Minor Improvements:

### PR DESCRIPTION
**Pull request by arturobernalg**
* Unnecessary boxing
* Unnecessary unboxing
* inline variable
* Change PosixParser to  DefaultParser

### CODE REVIEW

**Comment by ok2c** [comment]
@arturobernalg Would it be OK for you to put javadoc changes into a separate commit or PR? I suspect there are many more places where javadocs need some work.

**Comment by arturobernalg** [comment]
> @arturobernalg Would it be OK for you to put javadoc changes into a separate commit or PR? I suspect there are many more places where javadocs need some work.

Hi @ok2c . No problem. Do I need to create a Jira for the javadoc ?

**Comment by ok2c** [comment]
@arturobernalg I would not bother. Just raise a PR when ready.

**Comment by arturobernalg** [comment]
> @arturobernalg I would not bother. Just raise a PR when ready.

Hi @ok2c I've reverted the changes regarding the javaDoc. When i finish i'll provide another PR just only with javaDoc

TY

**Pull request merged**
