### PR TITLE
Httpcore 619 event mask as a class

### PR DESCRIPTION
**Pull request by garydgregory**
https://issues.apache.org/jira/browse/HTTPCORE-619

### CODE REVIEW

**Comment by michael-o** [comment]
@garydgregory Should this one be final?

**Comment by michael-o** [comment]
The branch is now uptodate and ready to be merged.

**Comment by garydgregory** [comment]
> 
> 
> The commit log looks like a mess. Please review, but otherwise the change is fine.
> 
> One could consider making the default constructor private, e.g.,
> 
> ```
>     private StandardCharsets() {
>         throw new AssertionError("No java.nio.charset.StandardCharsets instances for you!");
>     }
> ```

Please no, a final class and private default ctor yes, but just make the ctor body a comment like "// no instances."
Throwing an error here is just silly IMO.

**Comment by michael-o** [comment]
@garydgregory Please go ahead and amend the commit. If you are happy with everything else, please merge the amended commit to master.

**Comment by michael-o** [comment]
Looks good. Please do a fixup and merge to master.

**Pull request merged**
