### PR TITLE
Fix HTTPCORE-549

### PR DESCRIPTION
**Pull request by clevertension**
```
mvn -Powasp -Dtest=false -DfailIfNoTests=false clean org.owasp:dependency-check-maven:3.3.1:aggregate
```
will generate report in **target/dependency-check-report.html**
image

### CODE REVIEW

**Comment by ok2c** [comment]
@clevertension I think the parent project would be a better place for it. This way the plugin would need to be configured in each and every individual project. 

https://github.com/apache/httpcomponents-parent/

**Comment by clevertension** [comment]
good suggestion, i will add and test it ASAP

**Comment by clevertension** [comment]
done!!
https://github.com/apache/httpcomponents-parent/pull/1

**Comment by clevertension** [comment]
ok, i have reviewed it, it is no problem, so close this PR

**Pull request closed without merging**
