### PR TITLE
Use TimeWheel algorithm instead of loop when check timeout

### PR DESCRIPTION
**Pull request by xiaohu-zhang**
HashedWheelTimer and related util classes are copied from netty framework with tiny changes.
use TimeWheel algorithm  to deal with both connect time out and read time out.
related with HTTPCORE-484

### CODE REVIEW

**Comment by ok2c** [comment]
@xiaohu-zhang Why would you want to do that? Please re-apply your changes on top of master either by using `git rebase master` or manually.

**Comment by xiaohu-zhang** [comment]
I don't familiar with git and github.Please help me ,thank you very much,thank you !!
when at TimeWheel branch ,I use git rebase master ,there will be a lot of conflict.
when I at master ,I use git rebase TimeWheel, it is ok. but github web page says 
This branch is 99 commits ahead of apache:master. so I pull request will commit lots of change.
what can i do? thank you ,thank you very much,please help me ...I have try to slove it for 4 hours.cry..

**Comment by ok2c** [comment]
@xiaohu-zhang No problem. I'll pull in your changes and commit them to a separate branch for review

**Comment by xiaohu-zhang** [comment]
thank you,you are so kind. but there also lots of checksytle bugs in the pr. 
It is not ok to waste your time to cover for me。I will try to solve it tomorrow. thank you very much.

**Comment by xiaohu-zhang** [comment]
I wil try to solve it and pass ut then pr

**Pull request closed without merging**
